#!/bin/sh
diskpoint=$(diskutil list physical |head -n1 | awk -F "/"  '{print $3}' |awk '{print $1}')
sn=$(ioreg -rd1 -c IOPlatformExpertDevice | awk -F'"' '/IOPlatformSerialNumber/{print $4}')
echo current disk mount point is : $diskpoint
echo SN\: $sn
diskutil erasedisk APFS "Macintosh HD" $diskpoint
